### ISSUE TITLE
catkin_lint reports errors with CMakeLists.txt

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/softkinetic#16]
softkinetic_camera: error: build include path 'include' does not exist
softkinetic_camera: CMakeLists.txt(42): error: link_directories() must not be used for system depends
catkin_lint: checked 1 packages and found 2 problems
catkin_lint: 1 notices have been ignored. Use -W2 to see them

**Comment by corot** [comment]
As explained on issue #2, I suppose this is due to hardcoded `/opt/softkinetic` paths on CMakeLists.txt.

Would be great to change CMakeLists.txt so catkin can find softkinetic installation.
