### ISSUE TITLE
compilation error under hydro

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/softkinetic#2]
compiling with softkinetic installed under /opt/softkinetic throws a compile error for ros::Time::now() conversion to int64.

**Comment by floweisshardt** [comment]
@ipa-flg can we install the softkinetic sources inside the package directory? or is it fixed to /opt/softkinetic?

**Comment by kamiccolo** [comment]
Answering Your second question - yes, it is fixed to `/opt/softkinetic`.
However You could easily change that behaviour, check [CMakeList.txt](https://github.com/ipa320/softkinetic/blob/hydro_dev/softkinetic_camera/CMakeLists.txt) and all those hardcoded paths.

**Comment by ipa-flg** [comment]
error removed (see merge request #5 )

Concerning the package directory for DepthSenseSDK: 
Installing the softkinetic sources inside the package directory is definitely possible. However, I am not sure whether we should do that, as the SDK is only obtained by creating a (free) account on http://www.softkinetic.com/ . (See also respective package README)

**Comment by corot** [comment]
I think you can close this. Issue #16 keeps track of the problem with hardcoded `/opt/softkinetic` paths
