### ISSUE TITLE
Check if include_directories for suitesparse is still needed

### ISSUE THREAD

**Issue by abubeck** [ipa320/softkinetic#21]
There is an additional include_directories in CMakelists.txt for suitesparse. Please check, if this is required (seems odd).

**Comment by corot** [comment]
I removed on indigo without consequences

**Comment by fmessmer** [comment]
Has been removed in https://github.com/ipa320/softkinetic/commit/484eb9e782a82cba9c1c451be241be4c7ec4e5bd
