### ISSUE TITLE
Publish depth image and camera info

### ISSUE THREAD

**Issue by corot** [ipa320/softkinetic#26]
I have the code almost ready, thanks to @gavanderhoorn who did the heavy work. It includes mono and depth images and camera info for both depth and rgb cameras. I have tried to mirror the topics provided by openni-kinect. Also fixes issues #4 and #25. I'll PR as soon as PR https://github.com/ipa320/softkinetic/pull/27 gets resolved.

Talking about topic paths (issue #4), I use the following scheme (mimicking kinect), but I would be happy to change depth_registered by just depth, as it makes more sense to me. What do you think? Should I change something else? Maybe depth_registered/image should be depth_registered/image_raw

```
rgb/image_color
rgb/image_mono
rgb/camera_info
depth_registered/image
depth_registered/camera_info
depth_registered/points
```

**Comment by corot** [comment]
@jordi-pages, @efernandez, @ipa-flg, @ipa-nhg, and anyone else involved, please pay attention to this comment:
In fact, I'm changing the whole driver quite a lot, so... what about creating an indigo-devel branch with my new version? Like that people can compare easily with existing version, and optionally cherry pick to hydro the desired changes.

**Comment by efernandez** [comment]
@corot Sounds good to me!
AFAIK `depth_registered` means the depth image is in the same frame as the RGB one.
In some cases the `depth` and `depth_registered` images are the same, but for others like the Kinect it's not. I'm not sure which case applies to Softkinetic, but depending on that we should give the appropriate name to the topic.

**Comment by jordi-pages** [comment]
@corot 
I vote to rename 'depth_registered' to 'depth' and mention clearly in the ROS API whether these points are registered in the rgb frame.
Furthermore, I vote for 'depth/image_raw' as done in the openni2_camera node.

**Comment by gavanderhoorn** [comment]
@corot wrote:

> I have the code almost ready, thanks to @gavanderhoorn who did the heavy work [..]

I'm flattered, but I don't think I actually contributed to this, or did I? :) (my memory is a sieve sometimes).

Also: aren't there conventions for which topics should be published by a camera driver and under which names? See [wiki/camera_drivers](http://wiki.ros.org/camera_drivers) fi, and:
- [REP-118](http://www.ros.org/reps/rep-0118.html): Depth Images
- [REP-135](http://www.ros.org/reps/rep-0135.html): Driver Namespace Practices

**Comment by corot** [comment]
Done on indigo; we have now:
- rgb/image_color
- rgb/image_mono
- rgb/camera_info
- depth/image_raw
- depth/camera_info
- depth/points

**Comment by gavanderhoorn** [comment]
I also commented on #4.

**Comment by corot** [comment]
Following the effort for clearing PRs and issues... I suppose we only bugfix hydro (if so). As this is already implemented on indigo, we can close the issue
