### ISSUE TITLE
Apply recent indigo changes on hydro, reunifying both branches

### ISSUE THREAD

**Issue by corot** [ipa320/softkinetic#37]
The current status is:
- hydro_dev is the stable branch most people is using (afaik)
- indigo_dev is a deep review of the driver with many features and better performance, but not thoroughly tested.

I would suggest people to try indigo, as the benefits are notable. Once people have played around enough with the indigo version, and most problems are solved, I propose to reunify both branches and let only the strictly necessary differences. Of course, only if there's consensus about that!

**Comment by floweisshardt** [comment]
I support that, please see my comments in https://github.com/ipa320/softkinetic/pull/33#event-173944696 (merging hydro_dev into indigo_dev should always be possible, bringing changes from indigo_dev back to hydro requires cherry-picking)

**Comment by gavanderhoorn** [comment]
Yes, please try to avoid using github PRs for this. They bring in a lot of commits in the form of 'merging pull request from ..'. That could be intentional (preserving commit provenance), but when trying to keep two release branches in sync, it quickly pollutes the history of your repository. Especially when there is cross-syncing between branches.

**Comment by corot** [comment]
Well, actually I propose the opposite: pull request the recent changes on indigo to hydro, so both get unified on current indigo_dev basis. The merge will affect the ROS API, as on indigo we have adopted the existing conventions (see #4). That's why I ask people to give a try and approve indigo changes before applying them to hydro.

**Comment by corot** [comment]
Sorry, I see your comment now. The good thing of merging the branches is that they will appear as reunified on both the fork tree and when comparing branches. What's the alternative to PRs? Sorry, I'm not very experienced on managing github projects.

**Comment by gavanderhoorn** [comment]
@corot: @ipa-fmw already mentioned cherry-picking. Depending on the amount of changes you want to backport, that is a viable alternative. A regular command line merge might also be an option, leaving out the PR merges (although that removes the provenance information).

Unfortunately, choosing the _right_ way seems to be rather personal and based on the repository maintainers' preferences. I just wanted to draw attention to the fact that cross-branch syncing can become really ugly really soon.

**Comment by corot** [comment]
I'm not a git expert, but I suppose there must be a way to get both:
- merge both branches so they appear as reunified on the fork graph and the branch comparison table
- avoid the mob of commits on hydro_dev

Ideas:
- merge on github and collapse all commits into one (https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one)
- regular command line merge
- let hydro-dev untouched and let people PR the changes they really need
- any option I'm missing?

Selective cherry-picks will be risky and tedious, as incorporating only some improvements will easily break working, and I don't have enough time to do it properly step by step.

To be clear: I'm new here, so I let you choose.

Another point I want to remind here: indigo and hydro APIs are not compatible now, as on indigo we have adopted the existing conventions (see #4). So we should warn people using hydro before if we decide to merge.

**Comment by gavanderhoorn** [comment]
@corot: another nice write-up about squashing commits is [Squashing Github pull requests into a single commit ](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit/).

As to the options you list: I have no preference, I only wanted to point out that regular github PRs can quickly turn a nice history into spaghetti :).

**Comment by corot** [comment]
Following the effort for clearing PRs and issues... I suppose we only bugfix hydro (if so), so we can close this issue
