### ISSUE TITLE
`set_camera_info` service

### ISSUE THREAD

**Issue by youtalk** [ipa320/softkinetic#38]
[ROS camera driver](http://wiki.ros.org/camera_drivers) needs at least `image_raw` and `camera_info` topics and `set_camera_info` service. But `softkinetic_camera` has no `set_camera_info` service so far.

Do you have a plan to make it or should I? If I should make it, I start implementing after #37 issue solved.

**Comment by corot** [comment]
Not really, and I'm terribly busy these days. But why do you need issue 37? I suppose you must do this for indigo, as on hydro we don't have camera_info (I think). 

By the way, do you expect image_raw to provide color, or grayscale images?

**Comment by youtalk** [comment]
I mean I didn't know which branch I should use, but now it's ok. I start implementing on `indigo_dev`.

Oh, that was just an example for normal camera. I know you (or we) want `softkinetic_camera` functions to be the same as `openni_camera` functions, right? I also agree it :)

**Comment by corot** [comment]
Right, similar to openni_camera; I ask you about image_raw because we don't have still an image_raw topic: you must remap image_color or image_mono, until we implement issues #4.

**Comment by corot** [comment]
@youtalk, why did you close this?
